### ISSUE TITLE
input is disabled when asking for feedback

### ISSUE THREAD

**Issue by ajnart** [kodu-ai/claude-coder#17]
## Observed behavior
User was asked if they had any follow up question and the input to answer was disabled, sharing a "create" button instead

## Investigation needed
Understand why this happened

## Screenshots
![image](https://github.com/user-attachments/assets/b6aedb87-49b0-4aec-b834-2e67453dabdb)

**Comment by gagandt** [comment]
Tool buttons are set here
![Screenshot 2024-09-26 at 4 49 53 PM](https://github.com/user-attachments/assets/507a7191-a504-4f50-82ba-591515ecc6aa)

**Comment by gagandt** [comment]
The user will only see the buttons when autoApprove is off, and everytime we set the tool buttons, they are enabled on L350

![Screenshot 2024-09-26 at 4 51 41 PM](https://github.com/user-attachments/assets/b0933b6d-cb0a-4597-a772-c01b1c5f6c8c)
