### ISSUE TITLE
BUG: When doing multi-steps editing of a file, the agent takes the content from the initial file read

### ISSUE THREAD

**Issue by ajnart** [kodu-ai/claude-coder#52]
What the title says basically. It tried to add successive features like dark mode, copy to clipboard button, ... But did the new features based on the original file read and not the updated one. 

Sidenote I think this scenario is frustrating :  
- Ask Kodu to make a small change
- It does the change, there is a bug
- I fix the bug manually (a one liner / linter error) 
- Ask Kodu to make another change
- It makes the change but re-writes the file from where it was before, it doesn't take into account my bugfix

**Comment by matannahmani** [comment]
fixed on latest.
