### ISSUE TITLE
File writes are happening in real time

### ISSUE THREAD

**Issue by ajnart** [kodu-ai/claude-coder#54]
The file writes are happening in real time, not once you press save. Rejecting a file write reverts the state of the file to what the assistant thinks it should be. 

### Example 
- v1: Ask assistant to make small changes
- Changes are made
- I change the wording of a sentence in the code
- v2: Ask assistant to make another change
- Reject changes because it didn't work
- File is rolled back to v1

**Comment by matannahmani** [comment]
closed
