### ISSUE TITLE
Plugin is deleting file contents

### ISSUE THREAD

**Issue by nagv** [kodu-ai/claude-coder#70]
I was trying the plugin to add some new functionality. Realized the plugin is deleting existing code base part of adding new functionality. 
I am not sure whether plugin has limitation on number of lines it can process. I am trying to edit a file which has ~700 lines of code

**Comment by ajnart** [comment]
Hi @nagv, thank you for the report, it should be able to handle the full file. However, we have had reports that sometimes the LLM gets "lazy" and doesn't give out the full file with the changes. We're aware of this issue and are actively working to reduce this kind of issues

**Comment by matannahmani** [comment]
solved with inline edits ^
